// ---- 2D modular pixel hero (gpt-image-1 layered paper-doll) ----
// An original blue battle android (Mega Man-inspired, legally distinct) built as
// stacked pixel-art LAYERS: a base body + a swappable HELMET overlay, recoloured
// live with a hue rotation. This is what the in-game 'custom' agent renders.
// The layer art is generated by tools/genimg.py (--snap) and composited here on
// a shared 128px sprite frame (anchors tuned per part, like Aseprite layers).
import * as THREE from 'three';

export interface HeroConfig { helmet: string; hue: number }

// helmet overlays fitted to the base head box (centered x, target width + top y
// in the 512px composite). 'default' = the base's built-in helmet (no overlay).
export const HELMETS: Array<{ id: string; name: string; src?: string; w?: number; y?: number }> = [
  { id: 'default', name: 'Visor' },
  { id: 'hood', name: 'Hood', src: '/sprites/hero2d/helm_hood.png', w: 176, y: 26 },
  { id: 'oni', name: 'Oni', src: '/sprites/hero2d/helm_oni.png', w: 190, y: 14 },
];
const BASE_SRC = '/sprites/hero2d/base_front.png';
const BATTLE_SRC = '/sprites/hero2d/base_battle.png'; // three-quarter combat stance, buster to the right

const KEY = 'abyssal.hero2d';
export const DEFAULT_HERO: HeroConfig = { helmet: 'default', hue: 0 };

export function getHeroConfig(): HeroConfig {
  try {
    const raw = JSON.parse(localStorage.getItem(KEY) || 'null');
    if (raw && typeof raw === 'object') return { ...DEFAULT_HERO, ...raw };
  } catch { /* ignore */ }
  return { ...DEFAULT_HERO };
}
export function setHeroConfig(cfg: HeroConfig): void {
  try { localStorage.setItem(KEY, JSON.stringify(cfg)); } catch { /* ignore */ }
}

// ---- async image cache (redraw textures when a layer lands) ----
const _imgs = new Map<string, HTMLImageElement>();
const _waiters = new Map<string, Array<() => void>>();
function img(src: string): HTMLImageElement {
  let i = _imgs.get(src);
  if (!i) {
    i = new Image();
    i.onload = () => { const w = _waiters.get(src); if (w) for (const f of w.splice(0)) f(); };
    i.src = src; _imgs.set(src, i);
  }
  return i;
}
function onReady(srcs: string[], f: () => void) {
  let pending = 0;
  for (const s of srcs) {
    const i = img(s);
    if (i.complete && i.naturalWidth) continue;
    pending++;
    const w = _waiters.get(s) ?? []; w.push(() => { if (--pending <= 0) f(); }); _waiters.set(s, w);
  }
  if (pending === 0) f();
}

function helmetById(id: string) { return HELMETS.find((h) => h.id === id) ?? HELMETS[0]; }
function srcsFor(cfg: HeroConfig): string[] {
  const h = helmetById(cfg.helmet);
  return h.src ? [BASE_SRC, h.src] : [BASE_SRC];
}

// draw the composed hero (base + helmet overlay) into a 512-cell at ox, with an
// optional vertical bob; hue is applied by the caller's canvas filter.
function drawHero(x: CanvasRenderingContext2D, ox: number, cfg: HeroConfig, bob = 0) {
  const base = img(BASE_SRC);
  if (base.complete && base.naturalWidth) x.drawImage(base, ox, bob, 512, 512);
  const h = helmetById(cfg.helmet);
  if (h.src && h.w) {
    const hi = img(h.src);
    if (hi.complete && hi.naturalWidth) {
      const bb = trimBox(hi);
      const scale = h.w / bb.w;
      const dw = bb.w * scale, dh = bb.h * scale;
      const dx = ox + 256 - dw / 2, dy = (h.y ?? 30) + bob;
      x.drawImage(hi, bb.x, bb.y, bb.w, bb.h, dx, dy, dw, dh);
    }
  }
}

// trimmed opaque bounding box of an image (cached), so helmet art of any padding
// scales/positions by its real content.
const _bbox = new Map<string, { x: number; y: number; w: number; h: number }>();
function trimBox(im: HTMLImageElement) {
  const key = im.src;
  let b = _bbox.get(key);
  if (b) return b;
  const c = document.createElement('canvas'); c.width = im.naturalWidth; c.height = im.naturalHeight;
  const g = c.getContext('2d')!; g.drawImage(im, 0, 0);
  const d = g.getImageData(0, 0, c.width, c.height).data;
  let x0 = c.width, y0 = c.height, x1 = 0, y1 = 0;
  for (let y = 0; y < c.height; y++) for (let x = 0; x < c.width; x++) {
    if (d[(y * c.width + x) * 4 + 3] > 24) { if (x < x0) x0 = x; if (y < y0) y0 = y; if (x > x1) x1 = x; if (y > y1) y1 = y; }
  }
  b = x1 >= x0 ? { x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1 } : { x: 0, y: 0, w: c.width, h: c.height };
  _bbox.set(key, b); return b;
}

// ---- exporters (sprites.ts wraps these for the 'custom' body) ----
export function heroCanvas(cfg: HeroConfig): HTMLCanvasElement {
  const c = document.createElement('canvas'); c.width = c.height = 512;
  const x = c.getContext('2d')!; x.imageSmoothingEnabled = false;
  x.filter = `hue-rotate(${cfg.hue || 0}deg)`;
  drawHero(x, 0, cfg);
  return c;
}

// a horizontal N-frame strip with a gentle billboard bob (walk / battle idle)
export function heroStripCanvas(cfg: HeroConfig, frames: number, amp = 8): HTMLCanvasElement {
  const c = document.createElement('canvas'); c.width = 512 * frames; c.height = 512;
  const x = c.getContext('2d')!; x.imageSmoothingEnabled = false;
  x.filter = `hue-rotate(${cfg.hue || 0}deg)`;
  for (let i = 0; i < frames; i++) {
    const bob = -Math.abs(Math.sin((i / frames) * Math.PI * 2)) * amp;
    drawHero(x, i * 512, cfg, bob);
  }
  return c;
}

// ---- battle stance (separate three-quarter pose, faces +x toward the foe) ----
export type BattleKind = 'idle' | 'atk' | 'melee';
// katana blade tip ≈ far right, mid-height in the 512 frame (for the energy glint)
const MUZZLE = { x: 482, y: 240 };

function drawBattle(x: CanvasRenderingContext2D, ox: number, o: { bob?: number; dx?: number; flash?: number; slash?: number }) {
  const im = img(BATTLE_SRC);
  const dx = o.dx ?? 0, bob = o.bob ?? 0;
  if (im.complete && im.naturalWidth) x.drawImage(im, ox + dx, bob, 512, 512);
  if (o.flash) {
    const cx = ox + dx + MUZZLE.x, cy = MUZZLE.y + bob, r = 14 + o.flash * 18;
    const g = x.createRadialGradient(cx, cy, 0, cx, cy, r);
    g.addColorStop(0, 'rgba(255,255,255,0.95)'); g.addColorStop(0.4, 'rgba(120,240,255,0.8)'); g.addColorStop(1, 'rgba(120,240,255,0)');
    x.fillStyle = g; x.beginPath(); x.arc(cx, cy, r, 0, Math.PI * 2); x.fill();
  }
  if (o.slash) {
    const cx = ox + dx + 360, cy = 230 + bob;
    x.save(); x.strokeStyle = 'rgba(150,240,255,' + (0.7 * o.slash).toFixed(2) + ')'; x.lineWidth = 10;
    x.beginPath(); x.arc(cx, cy, 90 + o.slash * 20, -1.1, 0.7); x.stroke(); x.restore();
  }
}

export function heroBattleCanvas(cfg: HeroConfig, kind: BattleKind, frames: number): HTMLCanvasElement {
  const c = document.createElement('canvas'); c.width = 512 * frames; c.height = 512;
  const x = c.getContext('2d')!; x.imageSmoothingEnabled = false;
  x.filter = `hue-rotate(${cfg.hue || 0}deg)`;
  for (let i = 0; i < frames; i++) {
    const t = frames > 1 ? i / (frames - 1) : 0;
    const s = Math.sin(t * Math.PI); // 0→1→0 arc
    if (kind === 'idle') drawBattle(x, i * 512, { bob: -Math.abs(Math.sin((i / frames) * Math.PI * 2)) * 6 });
    else if (kind === 'atk') drawBattle(x, i * 512, { dx: s * 7, flash: t > 0.25 && t < 0.75 ? 1 : 0.15 }); // thrust + blade energy glint
    else drawBattle(x, i * 512, { dx: s * 12, slash: s }); // lunge + katana slash arc
  }
  return c;
}

function pixelTex(c: HTMLCanvasElement): THREE.Texture {
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace; t.magFilter = THREE.NearestFilter; t.anisotropy = 4;
  return t;
}

export function heroTexture(cfg: HeroConfig): THREE.Texture {
  const t = pixelTex(heroCanvas(cfg));
  onReady(srcsFor(cfg), () => { const c = heroCanvas(cfg); t.image = c; t.needsUpdate = true; });
  return t;
}
export function heroStripTexture(cfg: HeroConfig, frames: number, amp = 8): THREE.Texture {
  const t = pixelTex(heroStripCanvas(cfg, frames, amp));
  onReady(srcsFor(cfg), () => { const c = heroStripCanvas(cfg, frames, amp); t.image = c; t.needsUpdate = true; });
  return t;
}
export function heroBattleTexture(cfg: HeroConfig, kind: BattleKind, frames: number): THREE.Texture {
  const t = pixelTex(heroBattleCanvas(cfg, kind, frames));
  onReady([BATTLE_SRC], () => { const c = heroBattleCanvas(cfg, kind, frames); t.image = c; t.needsUpdate = true; });
  return t;
}
